# Generated by Django 5.1.7 on 2025-03-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allusers',
            name='spam_likelihood',
            field=models.FloatField(default=0.0),
        ),
    ]
