# Generated by Django 5.1.7 on 2025-03-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_searchindex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
