# Generated by Django 5.1.7 on 2025-03-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
